spring:
  datasource:
    url: jdbc:h2:mem:votes

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      ddl-auto: validate



  h2:
    console:
      enabled: true
